# Generated by Django 4.2.6 on 2023-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
